defmodule BackendWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :backend

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_backend_key",
    signing_salt: "GYXBp1sw",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :backend,
    gzip: not code_reloading?,
    only: BackendWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # CORS for the Nuxt frontend. Origins come from CORS_ORIGINS (comma-separated)
  # at runtime, defaulting to the Nuxt dev server — so deploying to Railway is a
  # config change, not a code change. cors_plug also answers OPTIONS preflight.
  plug CORSPlug, origin: &BackendWeb.Endpoint.cors_origins/0

  plug BackendWeb.Router

  @doc false
  def cors_origins do
    System.get_env("CORS_ORIGINS", "http://localhost:3000")
    |> String.split(",", trim: true)
    |> Enum.map(&String.trim/1)
  end
end
